# Generated by Django 5.1.6 on 2025-03-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
